Repository gregkrsak/phase-deuce, pull requests merged in 2020-05, with the labels that each got.

#14 Staging
  README.md
Labels: documentation

#25 Implemented command line arguments and -d or --date
  phase-deuce.py
Labels: enhancement

#27 Command line arguments now supported
  phase-deuce.py
Labels: documentation, enhancement

#29 Fix for #28
  phase-deuce.py
Labels: bug

#30 Significant code cleanup and exception handling improvements
  phase-deuce.py
Labels: bug, enhancement

#31 Significant code cleanup and exception handling improvements
  phase-deuce.py
Labels: bug, documentation, enhancement

#37 Docstring comment touchups
  phase-deuce.py
Labels: documentation

#38 Docstring and general comment enhancements
  phase-deuce.py
Labels: documentation
